import enum


class PAYMENT_METHOD(enum.Enum):
    PAYMENT_ON_DELIVERY = 'PAYMENT_ON_DELIVERY'
    CREDIT_CARD = 'CREDIT_CARD'
    DEBIT_CARD = 'DEBIT_CARD'


class ORDER_STATE(enum.Enum):
    CREATED = 'CREATED'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
