import { faker } from '@faker-js/faker';

describe('My First Test', () => {
  it('Visits the initial project page', () => {
    cy.visit('/user-sessions/login')
    cy.url().should('include', '/login')
  })
})

describe('Create Product Test', () => {
  beforeEach(() => {
    cy.visit('/user-sessions/login')
    cy.get('#email').type('admin.admin@sta.com')
    cy.get('#password').type('123456')
    cy.get('#doLogin').click()
    cy.url().should('include', '/home')
    cy.get('.menu-toggle').click()
    cy.get('#nav_products').click()
    cy.get('#nav_products_register').click()
  })
  it('Show Create Product Form Components', () => {
    cy.url().should('include', '/product/create')
    cy.contains('Crear Producto')
    cy.contains('Nombre')
    cy.get('#product_name').should('exist')
    cy.contains('Descripción')
    cy.get('#description').should('exist')
    cy.contains('Precio Unitario')
    cy.get('#unit_price').should('exist')
    cy.contains('Moneda')
    cy.get('#currency').should('exist')
    cy.contains('Categoría')
    cy.get('#category').should('exist')
    cy.contains('¿Es Promoción?')
    cy.get('#is_promotion').should('exist')
    cy.contains('Precio con Descuento')
    cy.get('#discount_price').should('exist').should('be.disabled')
    cy.contains('Fabricante')
    cy.get('#manufacturer').should('exist')
    cy.contains('Fecha de Vencimiento')
    cy.get('#expired_at').should('exist')
    cy.contains('Foto URL')
    cy.get('#url_photo').should('exist')
    cy.contains('Condiciones de Almacenamiento')
    cy.get('#store_conditions').should('exist')
  })

  it('Show Required Labels', () => {
    cy.get('#product_name').click()
    cy.get('#description').click()
    cy.get('#unit_price').click()
    cy.get('#currency')
    cy.window() 
    cy.get('#category')
    cy.window() 
    cy.get('#manufacturer')
    cy.window() 
    cy.contains('Foto URL')
    cy.get('#url_photo').click()
    cy.get('#store_conditions').click()
    cy.window() 
    cy.get('#product_name_required').should('exist')
    cy.get('#product_description_required').should('exist')
    cy.get('#product_unit_price_required').should('exist')
    cy.get('#product_url_photo_required').should('exist')
    cy.get('#product_store_conditions_required').should('exist')
    cy.get('.register-btn').should('exist').should('be.disabled')
  })

  it('Show Invalid Labels', () => {
    cy.get('#product_name').type(faker.lorem.words(100))
    cy.get('#product_name_exceed').should('exist')
    cy.get('#description').type(faker.lorem.words(100))
    cy.get('#product_description_exceed').should('exist')
    cy.get('#unit_price').type(faker.datatype.number({ min: -1000, max: -1 }).toString())
    cy.get('#is_promotion').check()
    cy.get('#is_promotion').check().should('be.checked')
    cy.get('#product_unit_price_invalid').should('exist')
    cy.get('#discount_price').should('exist').should('not.be.disabled')
    cy.get('#discount_price').type(faker.datatype.number({ min: -1000, max: -1 }).toString())
    cy.get('#url_photo').type(faker.lorem.word())
    cy.get('#product_discount_price_invalid').should('exist')
    cy.get('#product_url_photo_invalid').should('exist')
    cy.window() 
  })

  it('Fill Create Product Form SuccessFully', () => {
    cy.get('#product_name').type(faker.lorem.word())
    cy.get('#description').type(faker.lorem.word())
    cy.get('#unit_price').type(faker.datatype.number({ min: 1 }).toString())
    cy.get('#currency').select(1)
    cy.get('#manufacturer').select(1)
    cy.get('#category').select(1)
    cy.get('#is_promotion').check()
    cy.get('#is_promotion').check().should('be.checked')
    cy.get('#discount_price').should('exist').should('not.be.disabled')
    cy.get('#discount_price').type(faker.datatype.number({ min: 1 }).toString())
    cy.get('#url_photo').type(faker.image.imageUrl())
    cy.get('#store_conditions').type(faker.lorem.words(10))
    cy.get('.register-btn').should('exist').should('not.be.disabled')
    cy.get('.register-btn').click()
    cy.contains('El producto ha sido creado exitosamente')
  })
})