name: Push On Feature/Fix Branch.
on:
  push:
    branches:
      - 'feature/HU**'
      - 'fix/HU**'

jobs:
  general:
    name: General
    if: ${{ contains(github.event.head_commit.message, '[HU') }}
    runs-on: ubuntu-latest
    outputs:
      general_ok: ${{ steps.general.outputs.ok }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: general
        id: general
        run: echo "::set-output name=ok::true"

  stores_coverage:
    name: Stores Coverage
    needs: general
    if: ${{ needs.general.outputs.general_ok == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Python Env Configuration 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Locate in Stores
        run: cd stores
      - name: Install dependencies
        run: |
          python --version
          pip install --upgrade --no-cache-dir pip==23.2.1
          pip --version
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: |
          coverage run -m pytest -vv
      - name: Validate test
        if: ${{ failure() }}
        run: echo "One or more tests failed."
      - name: Validate coverage
        run: coverage report -m --fail-under=90